service: openspot-asg-scanner

provider:
  name: aws
  runtime: python3.8
  profile: openspot
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
      Resource: "*"

functions:
  hello:
    handler: handler.scan

custom:
  pythonRequirements:
    dockerizePip: true
