service: openspot-asg-scanner

provider:
  name: aws
  runtime: python3.8
  profile: openspot
  region: us-east-1
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "autoscaling:*"
      Resource: "*"

functions:
  scan:
    handler: handler.scan

custom:
  pythonRequirements:
    dockerizePip: true


plugins:
  - serverless-python-requirements
